// SPDX-License-Identifier: Apache-2.0
pragma solidity 0.8.37;

/// @title Quantize
/// @notice The weight quantization rule (briefs/leader-lookup.md as amended by leader-lookup-review.md, F2): the committed voting, leader,
/// reward and threshold weight q of a committee is derived from the raw bonded weights x, so that the committed total never exceeds the
/// profile cap B.
///
///     X = sum(x);  if X <= B:  q = x;  else  s = ceil(X / (B - n)),  q_i = max(1, floor(x_i / s)).
///
/// Σq <= X/s + n <= B and 1 <= q_i <= x_i. The same pure function is evaluated by the election (here), by bft-core's `evmassign.Quantize`
/// and by ureth's `quant::quantize`; `test/p85/fixtures/quant-vectors.json` (generated by `tools/quant_vectors.py`) is the shared vector set.
///
/// Security premise (F3): BFT safety assumes the Byzantine committed q-weight is below one third, not the raw stake. For any member subset S,
/// |q(S)/Q - x(S)/X| < 2n/Q, where Q = Σq; with Q > (B+1)/2 - n (about 32,700 at n = 64) the shift is under 0.4%.
library Quantize {
    /// @dev The profile cap on the total committed weight of a committee (the single constant of the bounded weighted leader lookup).
    uint256 internal constant WEIGHT_CAP_B = 65_536;

    error EmptyCommittee();
    error ZeroWeight();
    error CommitteeAboveCap();
    error WeightOverflow();

    /// @notice q = quant(x, n, B) for B = WEIGHT_CAP_B.
    function quantize(uint256[] memory x) internal pure returns (uint256[] memory q) {
        return quantize(x, WEIGHT_CAP_B);
    }

    /// @notice q = quant(x, n, b). Reverts on an empty committee, a zero weight, n >= b, or a raw total above 2^64 - 1 (the root's width).
    function quantize(uint256[] memory x, uint256 b) internal pure returns (uint256[] memory q) {
        uint256 n = x.length;
        if (n == 0) revert EmptyCommittee();
        if (n >= b) revert CommitteeAboveCap();
        uint256 total = 0;
        for (uint256 i = 0; i < n; ++i) {
            if (x[i] == 0) revert ZeroWeight();
            total += x[i];
            if (total > type(uint64).max) revert WeightOverflow();
        }
        q = new uint256[](n);
        if (total <= b) {
            for (uint256 i = 0; i < n; ++i) {
                q[i] = x[i];
            }
            return q;
        }
        uint256 s = (total + (b - n) - 1) / (b - n);
        for (uint256 i = 0; i < n; ++i) {
            uint256 v = x[i] / s;
            q[i] = v == 0 ? 1 : v;
        }
    }

    /// @notice The divisor of the rule for a raw total X and n members (1 when X <= b).
    function divisor(uint256 total, uint256 n, uint256 b) internal pure returns (uint256) {
        if (total <= b) return 1;
        return (total + (b - n) - 1) / (b - n);
    }
}
